repos:
  - repo: local
    hooks:
      - id: make-format
        name: Enforce C++ Formatting
        entry: make format
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: make-lint
        name: Enforce C++ Linting
        entry: make lint
        language: system
        pass_filenames: false
        stages: [pre-commit]
